#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AutodeskIdeaConnection.Droid.Resource", IsApplication=true)]

namespace AutodeskIdeaConnection.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::AutodeskIdeaConnection.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::AutodeskIdeaConnection.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int add1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int add2x = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int add3x = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int add4x = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int addGrey = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int addgrey1 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int addGrey2x = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int addGrey3x = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int addGrey4x = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int catArrow = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int catarrow1 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int catArrow2x = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int catArrow3x = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int catArrow4x = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int categories = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int categories1 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int categories2x = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int categories3x = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int categories4x = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int catGrey = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int catgrey1 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int catGrey2x = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int catGrey3x = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int catGrey4x = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int dislike = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int dislike1 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int dislike2x = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int dislike3x = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int dislike4x = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int feed = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int feed1 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int feed2x = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int feed3x = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int feed4x = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int feedGrey = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int feedgrey1 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int feedGrey2x = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int feedGrey3x = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int feedGrey4x = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int icon = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int like = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int like1 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int like2x = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int like3x = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int like4x = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int loading = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int loading1 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int loading2x = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int loading3x = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int loading4x = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int logo_copy = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int notifGrey = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int notifgrey1 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int notifGrey2x = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int notifGrey3x = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int notifGrey4x = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int notification = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int notification1 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int notification2x = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int notification3x = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int notification4x = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int success = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int success1 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int success2x = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int success3x = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int success4x = 2130837570;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
